#ifndef _CLIENT_IDENTITY_H_
#define _CLIENT_IDENTITY_H_

#include <string>

using namespace std;

/**
 * Class representing a client identity, uniquely generated by the Daemon in case of Dynamic and Secure clients
 * or by the dispatcher in case of Trusted clients. The Client Identity can be a unique number, or a hex sequence.
 * Do not make assumptions, do not try to forge your own client identity. 
 */
class ClientIdentity
{
public:

	/**
	 * Client Identity as a long number
	 */
	explicit ClientIdentity(unsigned long cid);

	/**
	 * Client Identity as a string
	 */
	explicit ClientIdentity(string cid);

	/**
	 * Returns the identity descriptor
	 */
	const string& getIdentityDescriptor() const;

private:

	// the identity descriptor of the client
	string identity;
};

#endif
